#!/usr/bin/perl
my @download_urls=();
foreach my $url (@ARGV) {
	if(!open(CURL, "curl $url|")) {
		warn "Unable to open URL \"$url\": $!\n";
		next;
	}
	while(<CURL>) {
		foreach my $imgurl (m#\bhref="(//[^"]*\.[a-z][a-z][a-z])"#g) {
			next if $imgurl =~ /\.(css|ico)$/;
			print "## ${imgurl}\n";
			$imgurl = "https:${imgurl}" if $imgurl =~ m#^//#;
			print "$imgurl\n";
			push @download_urls, $imgurl;
		}
	}
	close(CURL);
}

foreach $url (@download_urls) {
	system("curl -O $url");
}
