#!/usr/bin/env python2
import datetime
import sys
import re
import signal

sys.tracebacklimit = 0

def signal_handler(sig, frame):
    print("exiting")
    sys.exit(0)

def date_from_webkit(webkit_timestamp):
    epoch_start = datetime.datetime(1601,1,1)
    delta = datetime.timedelta(microseconds=int(webkit_timestamp))
    return epoch_start + delta

# Handle ^C and pipe breaking (e.g. killing PAGER)
signal.signal(signal.SIGINT, signal_handler)
signal.signal(signal.SIGPIPE, signal_handler)

for line in sys.stdin:
    match = re.search(r'"(\d\d\d\d\d\d\d+)"', line)
    if match:
        timestamp=match.group(1)
        date=date_from_webkit(timestamp)
        out=line.replace(timestamp, "%d-%02d-%02d %02d%02d.%02d" % (date.year, date.month, date.day, date.hour, date.minute, date.second))
        print out,
    else:
        print line,
