#!/usr/bin/env perl
use Text::Tabs;

my $width=`tput cols`-2;
my @lines=<>;
my $longest=0;
my $fmt = "%-*s  ";
my $fmtExtrasCount = length($fmt) - length("%-*s");

chomp @lines;
@lines = expand(@lines);

foreach $line (@lines) {
	my $len = length($line)+$fmtExtrasCount+1;
	if($len > $longest) {
		$longest = $len;
	}
}

my $columnCount = int($width / $longest);

my $column=0;
foreach $line (@lines) {
	my $len = length($line);
	printf($fmt, $longest, $line);
	unless(++$column < $columnCount) {
		print "\n";
		$column=0;
	}
}
print "\n" unless $column == 0;
