#!/usr/bin/env perl
my $width=`tput cols`-2;
my @lines=<>;
my $longest=0;

chomp @lines;
foreach $line (@lines) {
	my $len = length($line)+2;
	if($len > $longest) {
		$longest = $len;
	}
}

my $columnCount = int($width / $longest);

my $column=0;
foreach $line (@lines) {
	my $len = length($line);
	printf("%-*s", $longest, $line);
	if(++$column > $columnCount) {
		print "\n";
		$column=0;
	}
}
print "\n" unless $column == 0;
