#!/bin/sh
# set -x
all="+all-videos"
rm -rf "${all}"
mkdir -p "${all}"
# do mov first
exts="( -iname *.mov"
for ext in avi webm mp4 m4v mkv 3gp wmv flv vob ogv iso qt rm asf mpg mpeg mpv; do
	exts="${exts} -o -iname *.${ext}"
done
exts="${exts} )"

# echo "Command is: find . -type f ${exts} -print0"
find . -type f ${exts} -print0 | while read -d '' v; do
	# echo "## $v"
	dest="${all}/$v"
	if [ -r "$dest" ]; then
		# echo "## - already there"
		continue
	fi
	partial_path="${v%/*}"
	if [ "x${partial_path}" != "x${v}" ]; then
		dest_dir="${all}/${partial_path}"
		if [ ! -d "$dest_dir" ]; then
			# echo "### creating ${all}/${partial_path}"
			mkdir -p "$dest_dir"
		fi
		echo "${partial_path}"
	fi
	ln "$v" "${dest}"
	echo "    ${v##*/}"
done
