#!/bin/bash

offset=${1-0}
echo "Offset is $offset"

# assume web server points to a disk under /Volumes (typical for macOS)
dir="${PWD#/Volumes/}"
host="${HOSTNAME-$(hostname)}"
port=":${PORT-3030}"

# template for each video's web page
read -r -d '' html <<EOF
<!DOCTYPE html>
<html lang="en">
	<style>
	video {
	  width: 100%;
	  height: 100%;
	}
	</style>
<body>
	<div class="video-container">
		<video controls autoplay>
		  <source src="../%%FILENAME%%" type="video/mp4">
		</video>
	</div>
</body>
</html>
EOF

# make sure the "watch" dir is there
mkdir -p watch

# ignore * patterns that don't match anything
shopt -s nullglob

# assume video files are named .mp4 or .mkv or .m4v or something starting with 'm'
for video in *.{mp4,avi,mkv,m4v,webm,mov,flv,vob,ogv,ogg,ts,m2ts,qt,wmv,rm,asf,muddypawsgames@gmail.com,mpeg}; do
    basename="${video%%.???}"
    urlvideo=$(echo "$video" | perl -e 'use URI::Escape; $v=<>; chomp($v); $v =~ s#%#%%#g; print uri_escape_utf8($v);')
    echo "$basename"
    echo "$html" \
        | perl -p -e "s#%%FILENAME%%#${urlvideo}#;" \
	    > watch/"${basename}".html
done
echo ""
echo ""
echo ""
echo "> http://${host}${port}/${dir}"
echo ""
