#!/bin/bash

# Download this script and run to install everything on a new macOS
# including $HOME files

# debugging
# set -x

p() {
    echo ""
    echo "$(date) -- $*"
}

BREW_URL="https://raw.githubusercontent.com/Homebrew/install/master/install"

# cd to $HOME
cd

if [ ! -r /usr/local/bin/brew ]; then
	p Setting up homebrew
	/usr/bin/ruby -e "$(curl -fsSL ${BREW_URL})"

	# bring bash command cache up-to-date with now-installed "brew" command
	hash -r
fi

if [ ! -r /usr/bin/git ]; then
	p installing Xcode command line tools
	xcode-select --install
fi

if [ ! -r bin/noarch ]; then
	p Trying to use git to clone "'home'"
	git clone --recursive clith@clith.com:git/home
	mv -f .ssh .ssh-orig 2>/dev/null
	cd home
	mv -i * .[a-zA-Z0-9]* ~
	cd
	rmdir home
fi


# coretools include GNU ls et al.
installs=( \
	chocolate-doom \
	coretools \
	cvs \
	docker \
	ffmpeg \
	gnumeric \
	gnu-getopt \
	jove \
	jq \
	libdvdcss \
	media-info \
	p7zip \
	p7zip \
	telnet \
	wget \
	youtube-dl \
)
p installing $installs
brew install $installs

# The first time brew runs, it updates itself. Do not update Homebrew again
export HOMEBREW_NO_AUTO_UPDATE=1

# cask installs macOS apps in /Applications. These are grouped roughtly by smiilarity,
# and then alphabetical
# - not firefox
# - not google-chrome
p installing various casks to /Applications
casks=(\
	atom \
	qlmarkdown \
	WebPQuickLook \
	sublime-text \
	textmate \
	\
	colloquy \
	betterzip \
	discord \
	franz \
	go2shell \
	google-hangouts \
	iterm2 \
	signal \
	skype \
	slack \
	steam \
	telegram \
	tor-browser \
	transmission \
	whatsapp \
	wireshark \
	\
	adobe-dng-converter \
	\
	dropbox \
	google-backup-and-sync \
	zenmap \
	\
	4k-video-downloader \
	blender \
	freac \
	handbrake \
	krita \
	linein \
	makemkv \
	qlvideo \
	soundcloud-downloader \
	soundflower \
	vuescan \
	vlc \
	\
	asset-catalog-tinkerer \
	cocoscreator \
	devdocs \
	docker \
	docker-toolbox \
	gitup \
	godot \
	kitematic \
	qlswift \
	sourcetree \
	texturepacker \
	tiled \
	vagrant \
	virtualbox \
	virtualbox-extension-pack \
	\
	aerial \
	clipy \
	cyberduck \
	darktable \
	fission \
	gnucash \
	geotag \
	geotagger \
	hockey \
	iswiff \
	keybase \
	licecap \
	megasync \
	simple-comic \
	\
	adventure \
	angband \
	bzflag \
	gog-galaxy \
	ioquake3 \
	steamcmd \
	\
	geektool \
	mounty \
	postman \
	servetome \
	\
	mesasqlite \
	provisionql \
	qlmobi \
)

for cask in ${casks[*]}; do
	echo # `date` -- installing $cask
	brew cask install -q "$cask" || echo "## cask $cask failed"
done

p Setting up macOS
# defaults write com.apple.menuextra.battery ShowPercent YES
defaults write com.apple.menuextra.clock DateFormat "EEE MMM d  HH:mm"

#
# all of this is to simply set the default name of screenshots to yyyy-mm-dd.hhmm.ss.jpg
#
shotPList="~/Library/LaunchAgents/local.job.plist"
if [ ! -r "$shotPList" ]; then
	p "Setting up screenshots launchd job (will need to logout and log back in)"
	[ -d ~/Library/LaunchAgents ] || mkdir -p ~/Library/LaunchAgents
	cat > ~/Library/LaunchAgents/local.job.plist <<"EOF"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Disabled</key>   <false/>
	<key>Label</key>      <string>local.job</string>
	<key>Program</key>     <string>$HOME/bin/noarch-public/ss-rename</string>
	<key>RunAtLoad</key>  <true/>
	<key>WatchPaths</key> <array><string>$HOME/Desktop</string></array>
</dict>
</plist>
EOF
fi

p All done.
