#!/bin/bash

# debugging
# set -x

p() {
    echo ""
    echo "$(date) -- $*"
}

cd $HOME

if [ ! -r /usr/local/bin/brew ]; then
	p Setting up homebrew
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

	# bring bash up-to-date with now-installed "brew" commands
	hash -r
fi

if [ ! -r /usr/bin/git ]; then
	p installing Xcode command line tools
	xcode-select --install
fi

if [ ! -r bin/noarch ]; then
	p Trying to use git to clone "'home'"
	git clone --recursive clith@clith.com:git/home
	mv -f .ssh .ssh-orig 2>/dev/null
	cd home
	mv -i * .[a-zA-Z0-9]* ~
	cd
	rmdir home
fi


p installing JOVE, wget, cvs, p7zip
brew install jove wget cvs p7zip

#do not update Homebrew again
export HOMEBREW_NO_AUTO_UPDATE=1

p installing ffmpeg
brew install --with-libass --with-libbluray --with-libssh --with-libvidstab \
 --with-libvorbis --with-srt --with-tools --with-webp --with-x265 ffmpeg

p installing verious casks
brew cask install \
	textmate sublime-text postman sourcetree discord slack iterm2 google-chrome \
	google-drive-file-stream google-hangouts transmission vlc handbrake simple-comic \
	makemkv mounty dropbox fission aerial colloquy disk-inventory-x \
	steam steamcmd 4k-video-downloader ioquake3 licecap asset-catalog-tinkerer \
	telegram texturepacker freac franz gitifier gitup \
	darktable gnucash godot gog-galaxy adobe-dng-converter adventure chocolate-doom \
	angband bzflag cocoscreator cyberduck simple-comic devdocs servetome \
	discord keybase megasync mesasqlite qlmobi qlswift \
	provisionql qlvideo qlmarkdown

p Setting up macOS
# defaults write com.apple.menuextra.battery ShowPercent YES
defaults write com.apple.menuextra.clock DateFormat "EEE MMM d  HH:mm"

shotPList="~/Library/LaunchAgents/local.job.plist"
if [ ! -r "$shotPList" ]; then
	p Setting up screenshots launchd job (will need to logout and log back in)
	[ -d ~/Library/LaunchAgents ] || mkdir -p ~/Library/LaunchAgents
	cat > ~/Library/LaunchAgents/local.job.plist <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Disabled</key>
	<false/>
	<key>Label</key>
	<string>local.job</string>
	<key>Program</key>
	<string>$HOME/bin/noarch-public/ss-rename</string>
	<key>RunAtLoad</key>
	<true/>
	<key>WatchPaths</key>
	<array>
		<string>$HOME/Desktop</string>
	</array>
</dict>
</plist>
EOF
fi

p All done.
