#!/usr/bin/perl -ws
# renames screenshots on the desktop to 2020-02-02.1234.55.ext
#
my $dir = "$ENV{HOME}/Desktop";

sub d(@) {
	return unless $v;
	print @_;
	print "\n";
}

sub dd(@) {
	return unless $v;
	print @_;
}

if(scalar @ARGV > 0) {
	$dir = $ARGV[0];
	shift;
}
chdir($dir);

dd("PWD is ", `pwd`);

for my $ss (<"Screen Shot*">) {
	d("ss-rename: checking \"$ss\"");
	if($ss =~ /Screen Shot (\d\d\d\d-\d\d-\d\d) at (\d+)\.(\d\d\.\d\d)( [AP]M)?\.(\w\w\w)/) {
		my $date = $1;
		my $hour = $2;
		my $minutes = $3;
		d("ss-rename: renaming \"$ss\"");
		my $time=$2;
		if($4 eq " PM") {
			dd("ss-rename: adding 12 hours to $hour,");
			$hour += 12;
			d(" \"$hour\"");
		}
		$hour = "0${hour}" if $hour < 10;
		my $newname="${date}.${hour}${minutes}.${5}";
		if(-e $newname) {
			warn "$0: \"$newname\" already exists. skipping $ss\n";
			next;
		}
		d("ss-rename: renaming to \"$newname\"");
		rename $ss, $newname || print("ss-rename: renaming failed: $!\n");
	}
	elsif($ss =~ /Screen Shot (\d\d\d\d\-\d\d-\d\d) at (\d+)\.(\d\d\.\d\d) (am|pm)(.*)\.([a-z]+)$/i) {
		my $date = $1;
		my $hour = $2;
		my $minsec = $3;
		my $extra = $5;
		my $ext = $6;
		$hour += 12 if $4 =~ /[Pp][Mm]/;
		my $newname="${date}.${hour}${minsec}${extra}.${ext}";
		if(-e $newname) {
			warn "$0: \"$newname\" already exists. skipping $ss\n";
			next;
		}
		rename $ss, $newname;
	}
}

# Simulator Screen Shot - iPhone Xs Max (UAT, FR) - 2018-12-04 at 15.26.31
for my $ss (<"Simulator Screen Shot*">) {
	if($ss =~ /Simulator Screen Shot - (.*) - (\d\d\d\d\-\d\d-\d\d) at (\d\d)\.(\d\d\.\d\d)\.([a-z][a-z][a-z])/) {
		my $newname="simulator.${2}.${3}${4}.${1}.${5}";
		if(-e $newname) {
			warn "$0: \"$newname\" already exists. skipping $ss\n";
			next;
		}
		rename $ss, $newname;
	}
}
