#!/usr/bin/perl -w
# renames screenshots on the desktop that match "Screen Shot 2020-02-02 at 12.34.55.ext" to
# 2020-02-02.12.34.55.ext
#
chdir("$ENV{HOME}/Desktop");

for my $ss (<"Screen Shot*">) {
	if($ss =~ /Screen Shot (\d\d\d\d\-\d\d-\d\d) at (\d\d)\.(\d\d\.\d\d)\.([a-z]+)$/) {
		my $newname="${1}.${2}${3}.${4}";
		if(-e $newname) {
			warn "$0: \"$newname\" already exists. skipping $ss\n";
			next;
		}
		rename $ss, $newname;
	}
	elsif($ss =~ /Screen Shot (\d\d\d\d\-\d\d-\d\d) at (\d+)\.(\d\d\.\d\d) (am|pm)(.*)\.([a-z]+)$/i) {
		my $date = $1;
		my $hour = $2;
		my $minsec = $3;
		my $extra = $5;
		my $ext = $6;
		$hour += 12 if $4 =~ /[Pp][Mm]/;
		my $newname="${date}.${hour}${minsec}${extra}.${ext}";
		if(-e $newname) {
			warn "$0: \"$newname\" already exists. skipping $ss\n";
			next;
		}
		rename $ss, $newname;
	}
}

# Simulator Screen Shot - iPhone Xs Max (UAT, FR) - 2018-12-04 at 15.26.31
for my $ss (<"Simulator Screen Shot*">) {
	if($ss =~ /Simulator Screen Shot - (.*) - (\d\d\d\d\-\d\d-\d\d) at (\d\d)\.(\d\d\.\d\d)\.([a-z][a-z][a-z])/) {
		my $newname="simulator.${2}.${3}${4}.${1}.${5}";
		if(-e $newname) {
			warn "$0: \"$newname\" already exists. skipping $ss\n";
			next;
		}
		rename $ss, $newname;
	}
}
