#!/bin/sh

set -x

if [ $# != 4 ]; then
	echo "Usage: $0 start duration movie gif"
	exit 1
fi

start="$1"	# 00:00:00.000
duration="$2"	# 00:00:10.000
movie="$3"
gif="$4"

# tweak ffmpeg
# export AV_LOG_FORCE_NOCOLOR=1
# export FFREPORT="level=warning:"

# set -x

width=$(ffmpeg -i "${movie}" 2>&1 | grep -i video | perl -pe 's/^.* (\d\d\d+)x\d\d\d+[, ].*/${1}/;')

# temp files
palette="`mktemp -t vid2gif`.png"
filters="fps=15,scale=${width}:-1:flags=lanczos"

# get best pallette
ffmpeg -hide_banner -accurate_seek -loglevel warning -ss "${start}" -t "${duration}" -i "${movie}" \
	-vf "${filters},palettegen" -y $palette
ffmpeg -hide_banner -accurate_seek -loglevel warning -ss "${start}" -t "${duration}" -i "${movie}" \
	-i "${palette}" -filter_complex "${filters} [x]; [x][1:v] paletteuse" -y "${gif}"

# ffmpeg -accurate_seek -ss "${start}" -t "${duration}" -i "${movie}" -pix_fmt rgb24 -r 30 "${gif}"

echo "Finished $gif"

# clean up temp files
rm "${palette}"
